-- MySQL Script generated by MySQL Workbench
-- 09/24/18 10:35:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schoolshare
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `schoolshare` ;
CREATE SCHEMA IF NOT EXISTS `schoolshare` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `schoolshare` ;

-- -----------------------------------------------------
-- Table `schoolshare`.`instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolshare`.`instituicao` ;

CREATE TABLE IF NOT EXISTS `schoolshare`.`instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instituicao` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolshare`.`curso` ;

CREATE TABLE IF NOT EXISTS `schoolshare`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instituicao_id` INT NOT NULL,
  `curso` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_curso_Instituicao_idx` (`instituicao_id` ASC),
  CONSTRAINT `fk_curso_Instituicao`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `schoolshare`.`instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolshare`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `schoolshare`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `data_nascimento` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolshare`.`turma` ;

CREATE TABLE IF NOT EXISTS `schoolshare`.`turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `turma` VARCHAR(100) NOT NULL,
  `data_inicio` VARCHAR(10) NOT NULL,
  `data_final` VARCHAR(10) NOT NULL,
  `carga_horaria` SMALLINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_curso1_idx` (`curso_id` ASC),
  INDEX `fk_turma_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_turma_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `schoolshare`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `schoolshare`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolshare`.`matricula` ;

CREATE TABLE IF NOT EXISTS `schoolshare`.`matricula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `data_matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matricula_turma1_idx` (`turma_id` ASC),
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `schoolshare`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolshare`.`notas` ;

CREATE TABLE IF NOT EXISTS `schoolshare`.`notas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `nota_1` FLOAT NOT NULL DEFAULT 0,
  `nota_2` FLOAT NOT NULL DEFAULT 0,
  `nota_3` FLOAT NOT NULL DEFAULT 0,
  `nota_4` FLOAT NOT NULL DEFAULT 0,
  `frequencia` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacao_turma1_idx` (`turma_id` ASC),
  CONSTRAINT `fk_avaliacao_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `schoolshare`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`frequencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schoolshare`.`frequencia` ;

CREATE TABLE IF NOT EXISTS `schoolshare`.`frequencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `falta` TINYINT(1) NOT NULL,
  `data_frequencia` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_frequencia_turma1_idx` (`turma_id` ASC),
  INDEX `fk_frequencia_curso1_idx` (`curso_id` ASC),
  CONSTRAINT `fk_frequencia_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `schoolshare`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frequencia_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `schoolshare`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
