-- MySQL Script generated by MySQL Workbench
-- 09/03/18 10:36:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schoolshare
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `schoolshare` ;
CREATE SCHEMA IF NOT EXISTS `schoolshare` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `schoolshare` ;

-- -----------------------------------------------------
-- Table `schoolshare`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolshare`.`pessoa` (
  `id_pessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `tipo` TINYINT NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `nome_pai` VARCHAR(45) NOT NULL,
  `nome_mae` VARCHAR(45) NOT NULL,
  `cidade_nascimento` VARCHAR(45) NOT NULL,
  `estado_nascimento` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolshare`.`aluno` (
  `id_matricula` INT UNSIGNED NOT NULL,
  `pessoa_id_pessoa` INT UNSIGNED NOT NULL,
  `grau_escolariedade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pessoa_id_pessoa`, `id_matricula`),
  CONSTRAINT `fk_aluno_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `schoolshare`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolshare`.`professor` (
  `id_pessoa` INT NULL,
  `pessoa_id_pessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pessoa_id_pessoa`),
  CONSTRAINT `fk_professor_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `schoolshare`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolshare`.`instituicao` (
  `id_instituicao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`id_instituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolshare`.`turma` (
  `id_turma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `carga_horaria` SMALLINT(4) NOT NULL,
  `pessoa_id_pessoa` INT UNSIGNED NOT NULL,
  `professor_pessoa_id_pessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_turma`, `pessoa_id_pessoa`, `professor_pessoa_id_pessoa`),
  INDEX `fk_turma_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  INDEX `fk_turma_professor1_idx` (`professor_pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_turma_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `schoolshare`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`professor_pessoa_id_pessoa`)
    REFERENCES `schoolshare`.`professor` (`pessoa_id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolshare`.`matricula` (
  `id_matricula` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_matricula` DATE NOT NULL,
  `instituicao_id_instituicao` INT NOT NULL,
  `turma_id_turma` INT UNSIGNED NOT NULL,
  `aluno_pessoa_id_pessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_matricula`, `instituicao_id_instituicao`, `turma_id_turma`, `aluno_pessoa_id_pessoa`),
  INDEX `fk_matricula_instituicao_idx` (`instituicao_id_instituicao` ASC),
  INDEX `fk_matricula_turma1_idx` (`turma_id_turma` ASC),
  INDEX `fk_matricula_aluno1_idx` (`aluno_pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_matricula_instituicao`
    FOREIGN KEY (`instituicao_id_instituicao`)
    REFERENCES `schoolshare`.`instituicao` (`id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `schoolshare`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_pessoa_id_pessoa`)
    REFERENCES `schoolshare`.`aluno` (`pessoa_id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolshare`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolshare`.`admin` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id_pessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_admin`, `pessoa_id_pessoa`),
  INDEX `fk_admin_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_admin_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `schoolshare`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `schoolshare`.`pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `schoolshare`;
INSERT INTO `schoolshare`.`pessoa` (`id_pessoa`, `nome`, `email`, `sexo`, `data_nascimento`, `tipo`, `login`, `senha`, `ativo`, `cpf`, `rg`, `nome_pai`, `nome_mae`, `cidade_nascimento`,
 `estado_nascimento`, `nacionalidade`, `cep`, `rua`, `bairro`, `complemento`, `cidade`, `estado`, `telefone`, `celular`) VALUES 
(01, "java", "java@entra.com.br", "fem","2018-02-02" , "tipo", 'Admin', '6a4e4054fa6e08046c40df5745530cdde6e4e091de831d04d7d902635b9350ac', 
"02020202020", "123456", "pai", "mae", "blumenau", "brasileira", "89037260", "rua", "bairro", "ap", "blumenau", "sc", "33273588", 
"985648573");

COMMIT;

